language: node_js
sudo: false
node_js:
  - 8
install:
  - npm i vuepress macaca-ecosystem
  # https://github.com/webpack-contrib/terser-webpack-plugin/issues/66
  - npm i terser@3.14.1
script:
  - npm run docs:build
  - `npm bin`/macaca-ecosystem push --cwd ./docs_dist --branch gh-pages
  - npm i
  - npm run lint
  - npm run build
  - npm run test
after_script:
  - npm install coveralls@2 && cat ./coverage/lcov.info | coveralls
